- hosts: localhost
  tasks:
  - name: "DVD file Creating"
    file: 
          state: directory
          path: "/dvd"
  - name: "Mountin DVD"
    mount:
          src: "/dev/cdrom"
          path: "/dvd"
          state: mounted
          fstype: "iso9660"
  - name: "Creating yum repos dvd1"
    yum_repository:
          baseurl: "/dvd/AppStream"
          name: "dvd1"
          description: "mdvd1"
          gpgcheck: no
  - name: "Creating yum repos dvd2"
    yum_repository:
          baseurl: "/dvd/BaseOS"
          name: "dvd2"
          description: "mydvd2"
          gpgcheck: no
  - name: "Creating yum repos for docker"
    yum_repository:
          baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
          name: "docker"
          description: "docker-repo"
          gpgcheck: no
  - name: "Installing Docker-ce & python36"
    package:
          name: "docker-ce-18.09.1-3.el7.x86_64,python36"
  - name: "Starting & Enabling docker:"
    service: 
          name: "docker"
          state: started
          enabled: yes
  - name: "Installing docker library"
    pip:
          name: "docker"
  - name: "Pulling httpd from docker"
    docker_image:
          name: "httpd"
          source: pull
  - name: "Copying webpages"
    copy:
          dest: "/var/www/html/index.html"
          content: HERE IS COMPLETED TASK14.2                                                   "
  - name: "launching docker container"
    community.general.docker_container:
          name: "webserver1"
          image: "httpd"
          state: started
          exposed_ports:
                  - "80"
          volumes:
                  - /var/www/html:/usr/local/apache2/htdocs/
    register: dockerInfo
  - name: "Retrieving IP Add to new container"
    debug:
          var: dockerInfo.container.NetworkSettings.IPAddress
  - name: "Updating IP Address in Inventory of Ansible"
    blockinfile:
          dest: "/root/ip.txt"
          block: |
                  [Docker]
                  {{ dockerInfo['container']['NetworkSettings']['IPAddress']}} ansible_user=root ansible_ssh_pss=root ansible_connection=ssh
